"""empty message

Revision ID: 87e5b8a0fb4a
Revises: 
Create Date: 2018-12-11 15:10:11.426433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e5b8a0fb4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.String(length=100), nullable=True))
    op.add_column('book', sa.Column('bookList', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('dateRead', sa.DateTime(), nullable=True))
    op.add_column('book', sa.Column('yearOfPublication', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'yearOfPublication')
    op.drop_column('book', 'dateRead')
    op.drop_column('book', 'bookList')
    op.drop_column('book', 'author')
    # ### end Alembic commands ###
